### ISSUE TITLE
Investigate potential memory issue on Macs

### ISSUE THREAD

**Issue by jarrah42** [nova-model/nova-galaxy#19]
In GitLab by @gecage952 on Nov 8, 2024, 14:26 EST

A few Mac users are reporting seeing this intermittent error when using the Nova Galaxy library:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/gw6/Work/git/sammy/example/sammy.py", line 44, in main
    run_sammy_tool(conn, args.input, args.parameter, args.data)
  File "/Users/gw6/Work/git/sammy/example/sammy.py", line 22, in run_sammy_tool
    results = tool.run(datastore, params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gw6/Library/Caches/pypoetry/virtualenvs/sammy-YaHwWOGY-py3.12/lib/python3.12/site-packages/nova/galaxy/tool.py", line 59, in run
    galaxy_instance.jobs.wait_for_job(job_id=job["id"])
  File "/Users/gw6/Library/Caches/pypoetry/virtualenvs/sammy-YaHwWOGY-py3.12/lib/python3.12/site-packages/bioblend/galaxy/jobs/__init__.py", line 521, in wait_for_job
    return wait_on(check_and_get_job, maxwait=maxwait, interval=interval)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gw6/Library/Caches/pypoetry/virtualenvs/sammy-YaHwWOGY-py3.12/lib/python3.12/site-packages/bioblend/__init__.py", line 149, in wait_on
    return func()
           ^^^^^^
  File "/Users/gw6/Library/Caches/pypoetry/virtualenvs/sammy-YaHwWOGY-py3.12/lib/python3.12/site-packages/bioblend/galaxy/jobs/__init__.py", line 513, in check_and_get_job
    job = self.show_job(job_id)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gw6/Library/Caches/pypoetry/virtualenvs/sammy-YaHwWOGY-py3.12/lib/python3.12/site-packages/bioblend/galaxy/jobs/__init__.py", line 181, in show_job
    return self._get(id=job_id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gw6/Library/Caches/pypoetry/virtualenvs/sammy-YaHwWOGY-py3.12/lib/python3.12/site-packages/bioblend/galaxy/client.py", line 134, in _get
    raise ConnectionError(
bioblend.ConnectionError: HTTPSConnectionPool(host='calvera-test.ornl.gov', port=443): Max retries exceeded with url: /api/jobs/7fa601d582ccd147 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1062b2d80>: Failed to establish a new connection: [Errno 12] Cannot allocate memory')), 0 attempts left: 

```

*Migrated from GitLab: https://code.ornl.gov/ndip/public-packages/nova-galaxy/-/issues/16*

**Comment by jarrah42** [comment]
In GitLab by @gecage952 on Nov 8, 2024, 14:26 EST

added to epic ndip&186

**Comment by jarrah42** [comment]
In GitLab by @gecage952 on Nov 8, 2024, 14:28 EST

I haven't been able to reproduce this error on Linux. At any rate, some sort of investigation into this matter should be done.
